name: Java - Trigger SuperLinter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1 Checkout code
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Super-Linter
        uses: super-linter/super-linter@v8.0.0 # x-release-please-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
